import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const extensionRoot = path.resolve(scriptDir, "..");
const forgecadRoot = path.resolve(extensionRoot, "..", "..");
const vendorRoot = path.join(extensionRoot, "vendor");

const copies = [
  ["python/forgecad_core", "vendor/python/forgecad_core"],
  ["python/forgecad_service", "vendor/python/forgecad_service"],
  ["packages/webview-renderer", "vendor/webview-renderer"]
];

fs.rmSync(vendorRoot, { recursive: true, force: true });
fs.mkdirSync(vendorRoot, { recursive: true });

for (const [sourceRelative, targetRelative] of copies) {
  const source = path.join(forgecadRoot, sourceRelative);
  const target = path.join(extensionRoot, targetRelative);
  if (!fs.existsSync(source)) {
    throw new Error(`Missing ForgeCAD asset source: ${source}`);
  }
  fs.rmSync(target, { recursive: true, force: true });
  fs.mkdirSync(path.dirname(target), { recursive: true });
  fs.cpSync(source, target, {
    recursive: true,
    filter: (entry) =>
      !entry.includes(`${path.sep}node_modules${path.sep}`) &&
      !entry.endsWith(`${path.sep}node_modules`) &&
      !entry.includes(`${path.sep}__pycache__${path.sep}`) &&
      !entry.endsWith(`${path.sep}__pycache__`) &&
      !entry.includes(`${path.sep}.pytest_cache${path.sep}`) &&
      !entry.endsWith(`${path.sep}.pytest_cache`)
  });
}

const threeCadViewerDist = path.join(
  forgecadRoot,
  "packages",
  "webview-renderer",
  "node_modules",
  "three-cad-viewer",
  "dist"
);
if (!fs.existsSync(threeCadViewerDist)) {
  throw new Error(
    `Missing three-cad-viewer assets: ${threeCadViewerDist}. Run npm install in packages/webview-renderer.`
  );
}
fs.mkdirSync(path.join(vendorRoot, "webview-renderer", "three-cad-viewer"), {
  recursive: true
});
fs.cpSync(
  threeCadViewerDist,
  path.join(vendorRoot, "webview-renderer", "three-cad-viewer", "dist"),
  { recursive: true }
);

fs.writeFileSync(path.join(vendorRoot, ".generated"), "Generated by scripts/sync-assets.mjs\n");
console.log(`Synced ForgeCAD extension assets into ${vendorRoot}`);
